name: Validate

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master

env:
  NODE_VERSION: 20.14.0

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION}}

      - name: Install dependencies and validate linting and formatting
        run: |
          npm ci
          npm run validate
